name: Deploy usando archivo de clave EC2 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKERTOKEN }}" | docker login -u marcdelrio --password-stdin

      - name: Build y Push imagen
        run: |
          docker build -t marcdelrio/mi-web-nginx .
          docker push marcdelrio/mi-web-nginx
